export default [
  {
    departmentName: "Fashion",
    SubDepartments: [
      {
        subDName: "Womens Clothing",
        subCats: [
          { subCatName: "Dresses" },
          { subCatName: "Blouses n Shirts" },
          { subCatName: "Hoodies n Sweatshirts" },
          { subCatName: "Sweaters" },
          { subCatName: "Jackets n Coats" },
          { subCatName: "Bottoms" },
          { subCatName: "Rompers" },
          { subCatName: "Tops n Tees" },
          { subCatName: "Jumpsuits" },
          { subCatName: "Bodysuits" },
          { subCatName: "Suits n Sets" },
          { subCatName: "Dress" },
          { subCatName: "JeansSkirt" },
          { subCatName: "Swimsuit" },
          { subCatName: "Women Tops" },
          { subCatName: "Pants n Capris" },
        ],
      },
      {
        subDName: "Mens Clothing",
        subCats: [
          { subCatName: "Hoodies n Sweatshirts" },
          { subCatName: "Tops n Tees" },
          { subCatName: "Jackets n Coats" },
          { subCatName: "Pants" },
          { subCatName: "Shirts" },
          { subCatName: "Jeans" },
          { subCatName: "Sweaters" },
          { subCatName: "Suits n Blazers" },
          { subCatName: "Casual Shorts" },
          { subCatName: "Mens Sets" },
          { subCatName: "Board " },
          { subCatName: "Shorts" },
        ],
      },
      {
        subDName: "Womens Shoes",
        subCats: [
          { subCatName: "Womens Boots" },
          { subCatName: "Womens Flats" },
          { subCatName: "Womens Pumps" },
          { subCatName: "Womens Vulcanize Shoes" },
          { subCatName: "Womens Sandals" },
          { subCatName: "Running Shoes" },
          { subCatName: "Slippers" },
          { subCatName: "Flip Flops" },
          { subCatName: "Loafers" },
          { subCatName: "Oxfords" },
          { subCatName: "Boat Shoes" },
          { subCatName: "Heels" },
        ],
      },
      {
        subDName: "Mens Shoes",
        subCats: [
          { subCatName: "Mens Boots" },
          { subCatName: "Mens Casual Shoes" },
          { subCatName: "Mens Vulcanize Shoes" },
          { subCatName: "Loafers" },
          { subCatName: "Oxfords" },
          { subCatName: "Boat Shoes" },
          { subCatName: "Formal Shoes" },
          { subCatName: "Mens Sandals" },
          { subCatName: "Running Shoes" },
          { subCatName: "Slippers" },
          { subCatName: "Flip Flops" },
        ],
      },
      {
        subDName: "Shoe Accessories",
        subCats: [
          { subCatName: "Insoles" },
          { subCatName: "Shoelaces" },
          { subCatName: "Shoe Decorations" },
          { subCatName: "Shoes Covers" },
          { subCatName: "Inserts n Cushions" },
          { subCatName: "Shoe Trees" },
          { subCatName: "Shoe Care Kit" },
          { subCatName: "Shoe Horns" },
          { subCatName: "Ice Gripper" },
        ],
      },
      {
        subDName: "Baby",
        subCats: [
          { subCatName: "Baby n Toddler Toys" },
          { subCatName: "Baby Care" },
          { subCatName: "Diapering" },
          { subCatName: "Feeding" },
          { subCatName: "Gifts" },
          { subCatName: "Nursery" },
          { subCatName: "Potty Trainig" },
          { subCatName: "Safety" },
          { subCatName: "Pregnacy n Maternity" },
          { subCatName: "Travel Gear" },
        ],
      },
      {
        subDName: "Watches Parts n Accessories",
        subCats: [
          { subCatName: "Wristwatches" },
          { subCatName: "Wristwatch Bands" },
          { subCatName: "Pocket Watches" },
          { subCatName: "Watch Parts Tools n Guides" },
          { subCatName: "Watch Boxes Cases n Winders" },
          { subCatName: "Watch Batteries" },
        ],
      },
    ],
  },
  {
    departmentName: "Apparel Accessories",
    SubDepartments: [
      {
        subDName: "Womans Glasses",
        subCats: [
          { subCatName: "Eyewear Accessories" },
          { subCatName: "Womens Reading Glasses" },
          { subCatName: "Womens Sunglasses" },
          { subCatName: "Womens Eyewear Frames" },
          { subCatName: "Eyeglasses Lenses" },
          { subCatName: "Womens Night Vision Glasses" },
          { subCatName: "Womens Blue Light Blocking Glasses" },
        ],
      },
      {
        subDName: "Womens Hats",
        subCats: [
          { subCatName: "Womens Baseball Caps" },
          { subCatName: "Womens Berets" },
          { subCatName: "Womens Bomber Hats" },
          { subCatName: "Womens Bucket Hats" },
          { subCatName: "Womens Cowboy Hats" },
          { subCatName: "Womens Fedoras" },
          { subCatName: "Womens Military Hats" },
          { subCatName: "Womens Newsboy Caps" },
          { subCatName: "Womens Skullies n Beanies" },
          { subCatName: "Womens Sun Hats" },
          { subCatName: "Womens Visors" },
          { subCatName: "Womens Octagonal Hats" },
          { subCatName: "Womens Hip Hop Caps" },
        ],
      },
      {
        subDName: "Womens Scarves",
        subCats: [{ subCatName: "Womens Scarves" }],
      },
      {
        subDName: "Womens Hair Accessories",
        subCats: [{ subCatName: "Womens Hair Accessories" }],
      },
      {
        subDName: "Womens Gloves",
        subCats: [{ subCatName: "Womens Gloves" }],
      },
      {
        subDName: "Womens Belts",
        subCats: [{ subCatName: "Womens Belts" }],
      },
      {
        subDName: "Womans Accessories",
        subCats: [
          { subCatName: "Womens Sunglasses" },
          { subCatName: "Womens Baseball Caps" },
          { subCatName: "Womens Arm Warmers" },
          { subCatName: "Womens Earmuffs" },
          { subCatName: "Womens Scarf Sets" },
          { subCatName: "Womens Suspenders" },
          { subCatName: "Womens Ties n Handkerchiefs" },
          { subCatName: "Womens Masks" },
        ],
      },
      {
        subDName: "Mens Glasses",
        subCats: [
          { subCatName: "Eyewear Accessories" },
          { subCatName: "Mens Reading Glasses" },
          { subCatName: "Mens Sunglasses" },
          { subCatName: "Mens Eyewear Frames" },
          { subCatName: "Eyeglasses Lenses" },
          { subCatName: "Mens Night Vision Glasses" },
          { subCatName: "Mens Blue Light Blocking Glasses" },
        ],
      },
      {
        subDName: "Mens Hats",
        subCats: [
          { subCatName: "Mens Baseball Caps" },
          { subCatName: "Mens Bomber Hats" },
          { subCatName: "Mens Bucket Hats" },
          { subCatName: "Mens Cowboy Hats" },
          { subCatName: "Mens Fedoras" },
          { subCatName: "Mens Military Hats" },
          { subCatName: "Mens Newsboy Caps" },
          { subCatName: "Mens Skullies n Beanies" },
          { subCatName: "Mens Visors" },
          { subCatName: "Mens Sun Hats" },
          { subCatName: "Mens Berets" },
          { subCatName: "Mens Hip Hop Caps" },
        ],
      },
      {
        subDName: "Mens Scarves",
        subCats: [{ subCatName: "Mens Scarves" }],
      },
      {
        subDName: "Mens Belts",
        subCats: [
          { subCatName: "Belt Chains" },
          { subCatName: " Belt Buckles" },
        ],
      },
      {
        subDName: "Mens Gloves",
        subCats: [{ subCatName: "Mens Gloves" }],
      },
      {
        subDName: "Mens Ties n Handkerchiefs",
        subCats: [{ subCatName: "Mens Ties n Handkerchiefs" }],
      },
      {
        subDName: "Mens Accessories",
        subCats: [
          { subCatName: "Mens Arm Warmers" },
          { subCatName: "Mens Earmuffs" },
          { subCatName: "Mens Headbands" },
          { subCatName: "Mens Scarf Sets" },
          { subCatName: "Mens Suspenders" },
          { subCatName: "Mens Masks" },
        ],
      },
      {
        subDName: "Girls Accessories",
        subCats: [
          { subCatName: "Girls Hair Accessories" },
          { subCatName: "Girls Glasses" },
          { subCatName: "Girls Hats" },
          { subCatName: "Girls Scarves" },
          { subCatName: "Girls Hats,Scarves n Gloves Sets" },
          { subCatName: "Girls Gloves" },
          { subCatName: "Girls Belts" },
          { subCatName: "Girls Earmuffs" },
        ],
      },
      {
        subDName: "Boys Accessories",
        subCats: [
          { subCatName: "Boys Glasses" },
          { subCatName: "Boys Tie" },
          { subCatName: "Boys Hats" },
          { subCatName: "Boys Scarves" },
          { subCatName: "Boys Hats, Scarves n Gloves Sets" },
          { subCatName: "Boys Suspenders" },
          { subCatName: "Boys Belts" },
          { subCatName: "Boys Gloves" },
        ],
      },
      {
        subDName: "Garment Fabrics n Accessories",
        subCats: [
          { subCatName: "Lace Fabrics" },
          { subCatName: "Wax Fabrics" },
          { subCatName: "Wedding Dress Fabrics" },
          { subCatName: "Occasion Wear Fabrics" },
          { subCatName: "Garment Accessories n Samples" },
          { subCatName: "Garment Applique" },
          { subCatName: "Faux Leather Fabrics" },
          { subCatName: "Cotton Fabrics" },
          { subCatName: "Silk Fabrics" },
          { subCatName: "Sports n Leisure Wear Fabrics" },
          { subCatName: "Linen Fabrics" },
          { subCatName: "Suit Fabrics" },
        ],
      },
    ],
  },
  {
    departmentName: "Jewelry n Accessories",
    SubDepartments: [
      {
        subDName: "Fine Jewelry",
        subCats: [
          { subCatName: "Rings" },
          { subCatName: "Necklaces" },
          { subCatName: "Earrings" },
          { subCatName: "Pendants" },
          { subCatName: "Bracelets n Bangles" },
          { subCatName: "Jewelry Sets" },
          { subCatName: "Beads" },
          { subCatName: "Anklets" },
          { subCatName: "Charms" },
          { subCatName: "Hair Jewelry,Brooches n Body Jewelry" },
          { subCatName: "Loose Diamonds n Gemstones" },
        ],
      },
      {
        subDName: "Necklaces n Pendants",
        subCats: [
          { subCatName: "Pendant Necklaces" },
          { subCatName: "Chain Necklaces" },
          { subCatName: "Choker Necklaces" },
          { subCatName: "Pendants" },
          { subCatName: "Torques" },
          { subCatName: "Power Necklaces" },
        ],
      },
      {
        subDName: "Earrings",
        subCats: [
          { subCatName: "Stud Earrings" },
          { subCatName: "Drop Earrings" },
          { subCatName: "Hoop Earrings" },
          { subCatName: "Clip Earrings" },
        ],
      },
      {
        subDName: "Rings",
        subCats: [{ subCatName: "Womans Rings" }, { subCatName: "Mens Rings" }],
      },
      {
        subDName: "Bracelets n Bangles",
        subCats: [
          { subCatName: "Charm Bracelets" },
          { subCatName: "Chain n Link Bracelets" },
          { subCatName: "Bangles" },
          { subCatName: "Wrap Bracelets" },
          { subCatName: "Strand Bracelets" },
          { subCatName: "Cuff Bracelets" },
          { subCatName: "Hologram Bracelets" },
          { subCatName: "ID Bracelets" },
        ],
      },
      {
        subDName: "Beads n Jewelry Making",
        subCats: [
          { subCatName: "Beads" },
          { subCatName: "Jewelry Packaging n Display" },
          { subCatName: "Jewelry Findings n Components" },
          { subCatName: "Jewelry Tools n Equipments" },
        ],
      },
      {
        subDName: "Wedding n Engagement Jewelry",
        subCats: [
          { subCatName: "Bridal Jewelry Sets" },
          { subCatName: "Engagement Rings" },
          { subCatName: "Wedding Bands" },
        ],
      },
      {
        subDName: "Customized Jewelry",
        subCats: [
          { subCatName: "Customized Necklaces" },
          { subCatName: "Customized Key Chains" },
          { subCatName: "Customized Bracelets" },
          { subCatName: "Customized Rings" },
          { subCatName: "Customized Earrings" },
          { subCatName: "Customized Bangles" },
          { subCatName: "Other Customized Jewelry" },
          { subCatName: "Customized Beads" },
          { subCatName: "Customized Anklets" },
          { subCatName: "Customized Hair Jewelry" },
          { subCatName: "Customized Pendants" },
          { subCatName: "Customized Brooches" },
          { subCatName: "Customized Charms" },
        ],
      },
    ],
  },

  {
    departmentName: "Electronics",
    SubDepartments: [
      {
        subDName: "Cameras n Photo",
        subCats: [
          { subCatName: "Photo Studio" },
          { subCatName: "Camera n Photo Accessories" },
          { subCatName: "Digital Cameras" },
          { subCatName: "Camcorders" },
          { subCatName: "Camera Drones" },
          { subCatName: "Sports n Action Video Cameras" },
          { subCatName: "Lenses n Accessories" },
          { subCatName: "Tripod n Accessories" },
          { subCatName: "Selfie Sticks n Handheld Gimbal" },
          { subCatName: "Film Camera" },
          { subCatName: "Flashes n Accessories" },
          { subCatName: "Camera Replacement Parts" },
          { subCatName: "Camera Drones Accessories" },
          { subCatName: "Digital Photo Frame" },
        ],
      },
      {
        subDName: "Cellphones n Accessories",
        subCats: [{ subCatName: "" }],
      },
      {
        subDName: "Computer n Network",
        subCats: [
          { subCatName: "Computer Peripherals" },
          { subCatName: "Laptops" },
          { subCatName: "Tablets" },
          { subCatName: "Storage Devices" },
          { subCatName: "Computer Components" },
          { subCatName: "Networking" },
          { subCatName: "Mouse n Keyboards" },
          { subCatName: "Tablet Accessories" },
          { subCatName: "Laptop Accessories" },
          { subCatName: "Computer Cables n Connectors" },
          { subCatName: "Demo Board n Accessories" },
          { subCatName: "Mini PC" },
          { subCatName: "Industrial Computer n Accessories" },
          { subCatName: "Desktops" },
          { subCatName: "Servers" },
          { subCatName: "Device Cleaners" },
          { subCatName: "Laptop Parts" },
          { subCatName: "Tablet Parts" },
          { subCatName: "Office Software" },
        ],
      },
      {
        subDName: "eBook Readers",
        subCats: [{ subCatName: "" }],
      },
      {
        subDName: "Game Consoles n Accessories",
        subCats: [
          { subCatName: "Video Game Consoles" },
          { subCatName: "Handheld Game Players" },
          { subCatName: "Gamepads" },
          { subCatName: "Game Deals" },
          { subCatName: "Prepaid Digital Codes" },
          { subCatName: "Joysticks" },
          { subCatName: "Video Games Wheels" },
          { subCatName: "Fans" },
          { subCatName: "Batteries" },
          { subCatName: "Chargers" },
          { subCatName: "Harddisk n Boxs" },
          { subCatName: "Memory Cards" },
          { subCatName: "Bags" },
          { subCatName: "Cables" },
          { subCatName: "Cases" },
          { subCatName: "Stands" },
          { subCatName: "Screens" },
          { subCatName: "Screen Protectors" },
          { subCatName: "Game Peripherals" },
          { subCatName: "Nunchucks" },
          { subCatName: "Movement Sensors" },
          { subCatName: "Power Supplys" },
          { subCatName: "USB Receiver Adapter" },
          { subCatName: "Motion Plus" },
          { subCatName: "Replacement Parts n Accessories" },
          { subCatName: "Remotes" },
          { subCatName: "Stickers" },
          { subCatName: "Stylus" },
        ],
      },
      {
        subDName: "Headphones n Audio Devices",
        subCats: [
          { subCatName: "Phone Earphones" },
          { subCatName: "Bluetooth Earphones" },
          { subCatName: "Headphone or Headset" },
          { subCatName: "MP3 Players" },
          { subCatName: "Mini Speakers" },
          { subCatName: "AM FM Radios" },
          { subCatName: "Stereos" },
          { subCatName: "Boomboxes" },
        ],
      },
      {
        subDName: "Home Audio n Video",
        subCats: [
          { subCatName: "Projectors" },
          { subCatName: "Projectors Accessories n Parts" },
          { subCatName: "TV Receivers" },
          { subCatName: "TV Stick" },
          { subCatName: "Smart TV" },
          { subCatName: "Portable TV" },
          { subCatName: "LED Television" },
          { subCatName: "Home Theatre System" },
          { subCatName: "HDD Player" },
          { subCatName: "DVD n VCD Player" },
          { subCatName: "Blu-ray Player" },
          { subCatName: "Karaoke Player" },
          { subCatName: "Amplifier" },
          { subCatName: "Cassette Recorder n Player" },
        ],
      },
      {
        subDName: "Office Electronics",
        subCats: [
          { subCatName: "3D Printing n 3D Scanning" },
          { subCatName: "Printers" },
          { subCatName: "Printer Supplies" },
          { subCatName: "Printer Parts n Accessories" },
          { subCatName: "Scanners" },
          { subCatName: "Calculators" },
          { subCatName: "Conference System" },
          { subCatName: "Laminator" },
          { subCatName: "Paper Trimmer" },
          { subCatName: "Money Counter s Detector" },
          { subCatName: "Fax machines n Copiers" },
          { subCatName: "Shredder" },
          { subCatName: "Network Print Servers" },
          { subCatName: "Binding Machine" },
          { subCatName: "Graph Plotter" },
          { subCatName: "Time Recording" },
          { subCatName: "Visual Presenter" },
        ],
      },
      {
        subDName: "Service Plans",
        subCats: [
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
        ],
      },
      {
        subDName: "Television n Video",
        subCats: [
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
          { subCatName: "" },
        ],
      },
      {
        subDName: "Wearable Technology",
        subCats: [
          { subCatName: "Smart Watches" },
          { subCatName: "Smart Accessories" },
          { subCatName: "Smart Wristbands" },
          { subCatName: "Smart Activity Trackers" },
        ],
      },
    ],
  },
  {
    departmentName: "Health n Beauty",
    SubDepartments: [
      {
        subDName: "Makeup",
        subCats: [
          { subCatName: "Eyes" },
          { subCatName: "Makeup Tools n Accessories" },
          { subCatName: "Face" },
          { subCatName: "Lips" },
          { subCatName: "Makeup Sets" },
          { subCatName: "Body" },
          { subCatName: "Makeup Remover" },
          { subCatName: "Makeup Brushes n Tools" },
          { subCatName: "False Eyelashes" },
        ],
      },
      {
        subDName: "Skin Care",
        subCats: [
          { subCatName: "Face" },
          { subCatName: "Sun" },
          { subCatName: "Feet" },
          { subCatName: "Essential Oil" },
          { subCatName: "Breast Enhancement Cream" },
          { subCatName: "Eyes" },
          { subCatName: "Body" },
          { subCatName: "Hands n Nails" },
          { subCatName: "Lips" },
          { subCatName: "Maternity" },
          { subCatName: "Neck" },
          { subCatName: "Sets" },
          { subCatName: "Skin Care Tool" },
        ],
      },
      {
        subDName: "Sex Products",
        subCats: [
          { subCatName: "Safer Sex" },
          { subCatName: "Sex Toys" },
          { subCatName: "SM Products" },
        ],
      },
      {
        subDName: "Hair Care n Styling",
        subCats: [
          { subCatName: "Styling Tools" },
          { subCatName: "Hair Color" },
          { subCatName: "Hair Loss Products" },
          { subCatName: "Hair n Scalp Treatments" },
          { subCatName: "Shampoos" },
          { subCatName: "Hair Care Sets" },
          { subCatName: "Conditioners" },
          { subCatName: "Hair Perms n Texturizers" },
          { subCatName: "Hair Relaxers" },
          { subCatName: "Styling Products" },
          { subCatName: "Curling Irons" },
          { subCatName: "Hair Dryers" },
          { subCatName: "Straightening Irons" },
          { subCatName: "Hair Trimmers" },
        ],
      },
      {
        subDName: "Health Care",
        subCats: [
          { subCatName: "Slimming Creams" },
          { subCatName: "Household Health Monitors" },
          { subCatName: "Chinese Medicine" },
          { subCatName: "Massage Products" },
          { subCatName: "Personal Health Care" },
          { subCatName: "Mobility Aids" },
          { subCatName: "Contact lenses" },
          { subCatName: "Health Food" },
          { subCatName: "Massage n Relaxation" },
        ],
      },
      {
        subDName: "Tools n Accessories",
        subCats: [
          { subCatName: "Cotton Swabs" },
          { subCatName: "Hand Rests" },
          { subCatName: "Makeup Tools n Accessories" },
        ],
      },
      {
        subDName: "Shaving n Hair Removal",
        subCats: [
          { subCatName: "Razor Blade" },
          { subCatName: "Razor" },
          { subCatName: "Hair Removal Cream" },
          { subCatName: "Nose n Ear Trimmer" },
          { subCatName: "Shaving Brush" },
          { subCatName: "Shaving Cream" },
          { subCatName: "Shaving Foam" },
          { subCatName: "Aftershave" },
          { subCatName: "Electric Shavers" },
          { subCatName: "Epilator" },
          { subCatName: "Waxing" },
        ],
      },
      {
        subDName: "Beauty Equipment",
        subCats: [
          { subCatName: "Derma Roller" },
          { subCatName: "LED Skin Rejuvenation Machine" },
          { subCatName: "Skin Beauty Cleansing Facial Bubble Machine" },
          { subCatName: "Microdermabrasion Peel Machine" },
          { subCatName: "Water Oxygen Facial Machine" },
          { subCatName: "Skin Analyzer Machine" },
          { subCatName: "Magnifying Lamp" },
        ],
      },
      {
        subDName: "Beauty Essentials",
        subCats: [
          { subCatName: "False Eyelashes" },
          { subCatName: "Eye Shadow" },
          { subCatName: "Makeup Brushes n Tools" },
          { subCatName: "Lipstick" },
          { subCatName: "Eyebrow Enhancers" },
          { subCatName: "Eyeliner" },
          { subCatName: "Mascara" },
          { subCatName: "BB n CC Creams" },
          { subCatName: "Cosmetic Puff" },
          { subCatName: "Powder" },
          { subCatName: "Day Creams n Moisturizers" },
          { subCatName: "Toners" },
        ],
      },
      {
        subDName: "Sanitary Paper",
        subCats: [
          { subCatName: "Toilet Tissue" },
          { subCatName: "Wet Wipes" },
          { subCatName: "Paper Napkins n Serviettes" },
          { subCatName: "Facial Tissue" },
          { subCatName: "Adult Diapers" },
        ],
      },
      {
        subDName: "Tattoo n Body Art",
        subCats: [
          { subCatName: "Tattoo Grips" },
          { subCatName: "Tattoo Guns" },
          { subCatName: "Tattoo Inks" },
          { subCatName: "Tattoo Kits" },
          { subCatName: "Tattoo Needles" },
          { subCatName: "Tattoo Power Supply" },
          { subCatName: "Tattoo Stencils" },
          { subCatName: "Tattoo Tips" },
          { subCatName: "Tattoo accesories" },
          { subCatName: "Temporary Tattoos" },
          { subCatName: "Eyebrow Tattoo Machine" },
          { subCatName: "Permanent Makeup Machine" },
        ],
      },
      {
        subDName: "Bath n Shower",
        subCats: [
          { subCatName: "Cleansers" },
          { subCatName: "Bath" },
          { subCatName: "Scrubs n Bodys Treatments" },
          { subCatName: "Sets" },
        ],
      },
      {
        subDName: "Oral Hygiene",
        subCats: [
          { subCatName: "Electric Toothbrush" },
          { subCatName: "Teeth Whitening" },
          { subCatName: "Toothbrushes" },
          { subCatName: "Oral Irrigator" },
          { subCatName: "Toothbrushes Head" },
          { subCatName: "Toothpaste" },
          { subCatName: "Dental Supplies" },
          { subCatName: "Dental Flosser" },
          { subCatName: "Interdental Brush" },
          { subCatName: "Toothbrush Sanitizer" },
          { subCatName: "Dental Teaching Model" },
          { subCatName: "Dental Cultural Product" },
          { subCatName: "Dental Chair Cover" },
        ],
      },
      {
        subDName: "Fragrances n Deodorants",
        subCats: [{ subCatName: "Deodorants n Antiperspirants" }],
      },
      {
        subDName: "Bathing n Shower",
        subCats: [
          { subCatName: "Cleansers" },
          { subCatName: "Bath" },
          { subCatName: "Scrubs n Bodys Treatments" },
          { subCatName: "Sets" },
        ],
      },
      {
        subDName: "Skin Care Tools",
        subCats: [
          { subCatName: "Refillable Bottles" },
          { subCatName: "Blackhead n Blemish Removers" },
          { subCatName: "Facial Care Tools" },
          { subCatName: "Mirrors" },
          { subCatName: "Foot Care Tool" },
          { subCatName: "Face Lift Tools" },
          { subCatName: "Powered Facial Cleansing Devices" },
          { subCatName: "Eye Care Tools" },
          { subCatName: "LED Mask" },
          { subCatName: "Ion Device" },
          { subCatName: "Skin Scrubber" },
          { subCatName: "Sonic Vibrating Device" },
          { subCatName: "Microcurrent Device" },
          { subCatName: "Skin Analyzer" },
        ],
      },
    ],
  },
  {
    departmentName: "Movies n Music",
    SubDepartments: [
      {
        subDName: "Pro Audio Equipment",
        subCats: [
          { subCatName: "Speakers & Subwoofers" },
          { subCatName: "PA Systems" },
          { subCatName: "Mixers" },
          { subCatName: "PROCESSORS n AMPLIFIERS" },
          { subCatName: "Cabled, Stands n accessories" },
          { subCatName: "Stages n trussing" },
          { subCatName: "Line array n concert sound" },
        ],
      },
      {
        subDName: "Musical Instruments n Gear",
        subCats: [
          { subCatName: "Guitars n Basses" },
          { subCatName: "Percussion Instruments" },
          { subCatName: "Wind n Woodwind Instruments" },
          { subCatName: "String Instruments" },
          { subCatName: "Pianos Keyboards n Organs" },
        ],
      },
      {
        subDName: "DVD n Movies",
        subCats: [
          { subCatName: "DVDs n Bluray Disks" },
          { subCatName: "VHS Tapes" },
          { subCatName: "Other Movie Formats" },
          { subCatName: "Movie Film Stock" },
          { subCatName: "LaserDisk Movies" },
          { subCatName: "DVD n Movies Wholesale Lots" },
        ],
      },
      {
        subDName: "Music",
        subCats: [
          { subCatName: "Music CDs" },
          { subCatName: "Vinyl Records" },
          { subCatName: "Other Formats" },
          { subCatName: "Cassettes" },
          { subCatName: "Music Storage" },
          { subCatName: "Media Accessories" },
          { subCatName: "Rocorded Music Wholesale Lots" },
        ],
      },
    ],
  },
  {
    departmentName: "Home n Garden",
    SubDepartments: [
      {
        subDName: "Kitchen,Dining n Bar",
        subCats: [
          { subCatName: "Coffeeware" },
          { subCatName: "Teaware" },
          { subCatName: "Barware" },
          { subCatName: "Bakeware" },
          { subCatName: "Dinnerware" },
          { subCatName: "Drinkware" },
          { subCatName: "Flatware" },
          { subCatName: "Cookware n Parts" },
          { subCatName: "Table Decoration n Accessories" },
          { subCatName: "Kitchen Knives n Accessories" },
          { subCatName: "Manual Food Processors" },
          { subCatName: "Home Brewing n Wine Making" },
          { subCatName: "Fruit n Vegetable Tools" },
          { subCatName: "Measuring Tools n Scales" },
          { subCatName: "Egg Tools" },
          { subCatName: "Cheese Tools" },
          { subCatName: "Dessert Tools" },
          { subCatName: "Herb n Spice Tools" },
          { subCatName: "Ice Cream Tools" },
          { subCatName: "Meat n Poultry Tools" },
          { subCatName: "Utensils" },
          { subCatName: "Other Kitchen Tools n Gadgets" },
          { subCatName: "Disposable Kitchenware" },
        ],
      },
      {
        subDName: "Home Decor",
        subCats: [
          { subCatName: "Wall Stickers" },
          { subCatName: "Painting n Calligraphy" },
          { subCatName: "Ornaments" },
          { subCatName: "Clocks" },
          { subCatName: "Photo Albums" },
          { subCatName: "Candles n Holders" },
          { subCatName: "Frame" },
          { subCatName: "Vases" },
          { subCatName: "Plaques n Signs" },
          { subCatName: "Wind Chimes n Hanging Decorations" },
          { subCatName: "Figurines n Miniatures" },
          { subCatName: "Statues n Sculptures" },
          { subCatName: "Flags, Banners n Accessories" },
          { subCatName: "Blinds, Shades n Shutters" },
          { subCatName: "Curtain Decorative Accessories" },
          { subCatName: "Incense n Incense Burners" },
          { subCatName: "Decorative Mirrors" },
          { subCatName: "Money Boxes" },
          { subCatName: "Music Boxes" },
          { subCatName: "Screens n Room Dividers" },
          { subCatName: "Decorative Films" },
          { subCatName: "Window Treatments" },
          { subCatName: "Reed Diffusers, Oils n Accessories" },
          { subCatName: "Christian Decor" },
          { subCatName: "Door Stickers" },
        ],
      },
      {
        subDName: "Arts Crafts n Sewing",
        subCats: [
          { subCatName: "Apparel Sewing n Fabric" },
          { subCatName: "Needle Arts n Crafts" },
          { subCatName: "Fabric" },
          { subCatName: "Cross-Stitch" },
          { subCatName: "Diamond Painting Cross Stitch" },
          { subCatName: "Sewing Machines" },
          { subCatName: "Scrapbooking n Stamping" },
          { subCatName: "Embossing" },
          { subCatName: "Pottery n Ceramics" },
          { subCatName: "Leathercraft" },
          { subCatName: "Candle Making" },
          { subCatName: "Button n Badge Making" },
          { subCatName: "Soap Making" },
          { subCatName: "Felt DIY Craft" },
          { subCatName: "Mosaic Making" },
          { subCatName: "Wood DIY Crafts" },
          { subCatName: "Arts, Crafts n Sewing Storage" },
          { subCatName: "DIY Knitting" },
          { subCatName: "Paint By Number" },
          { subCatName: "Paint By Number Accessories" },
          { subCatName: "Fabric Decorating" },
          { subCatName: "Customized Garment accessories" },
          { subCatName: "Customized Craft" },
          { subCatName: "DIY Scratch Painting" },
        ],
      },
      {
        subDName: "Festive n Party Supplies",
        subCats: [
          { subCatName: "Event n Party" },
          { subCatName: "Christmas" },
          { subCatName: "Artificial Decorations" },
          { subCatName: "Wedding Decorations" },
          { subCatName: "Customized Party Supplies" },
          { subCatName: "Customized Gift Wrapping n Cards" },
        ],
      },
      {
        subDName: "Home Storage n Organization",
        subCats: [
          { subCatName: "Clothing n Wardrobe Storage" },
          { subCatName: "Kitchen Storage n Organization" },
          { subCatName: "Laundry Storage n Organization" },
          { subCatName: "Bathroom Storage n Organization" },
          { subCatName: "Home Office Storage" },
          { subCatName: "Hooks n Rails" },
          { subCatName: "Storage Bags" },
          { subCatName: "Storage Baskets" },
          { subCatName: "Storage Bottles n Jars" },
          { subCatName: "Storage Boxes n Bins" },
          { subCatName: "Storage Drawers" },
          { subCatName: "Storage Holders n Racks" },
          { subCatName: "Air Vacuum Bags" },
          { subCatName: "Vacuum Bag Pumps" },
        ],
      },
      {
        subDName: "Bathroom Products",
        subCats: [
          { subCatName: "Bath Brushes, Sponges n Scrubbers" },
          { subCatName: "Bath Mats" },
          { subCatName: "Bath Pillows" },
          { subCatName: "Bathroom Scales" },
          { subCatName: "Shower Caps" },
          { subCatName: "Shower Curtain Poles" },
          { subCatName: "Shower Curtains" },
          { subCatName: "Toilet Plungers" },
          { subCatName: "Toilet Seat Covers" },
          { subCatName: "Inflatable n Portable Bathtubs" },
          { subCatName: "Bathroom Gadgets" },
          { subCatName: "Portable Soap Dishes" },
          { subCatName: "Portable Soap Dispensers" },
          { subCatName: "Bathroom Tumblers" },
          { subCatName: "Toothbrush n Toothpaste Holders" },
          { subCatName: "Portable Toilet Paper Holders" },
          { subCatName: "Plastic n Portable Basins" },
          { subCatName: "Bathroom Accessories Sets" },
          { subCatName: "Toilet Brushes" },
        ],
      },
      {
        subDName: "Household Cleaning",
        subCats: [
          { subCatName: "Household Cleaning Tools" },
          { subCatName: "Laundry Products" },
          { subCatName: "Household Cleaning Protections" },
          { subCatName: "Household Chemicals" },
        ],
      },
      {
        subDName: "Pet Products",
        subCats: [
          { subCatName: "Dog Clothing n Shoes" },
          { subCatName: "Dog Collars n Leads" },
          { subCatName: "Dog Feeding" },
          { subCatName: "Dog Grooming" },
          { subCatName: "Dog Doors, Houses n Furniture" },
          { subCatName: "Dog Toys" },
          { subCatName: "Dog Training Aids" },
          { subCatName: "Dog Carriers" },
          { subCatName: "Dog Litter n Housebreaking" },
          { subCatName: "Cat Supplies" },
          { subCatName: "Fish n Aquatic Supplies" },
          { subCatName: "Reptile n Amphibian Supplies" },
          { subCatName: "Small Animal Supplies" },
          { subCatName: "Bird Supplies" },
          { subCatName: "Insect Supplies" },
          { subCatName: "Farm Animal Supplies" },
          { subCatName: "Pet Thermometers" },
          { subCatName: "Pet Memorials" },
          { subCatName: "GPS Trackers" },
          { subCatName: "Pet Microchips" },
          { subCatName: "Pet Health Care n Hygiene" },
          { subCatName: "Pet Medical Supplies" },
        ],
      },
      {
        subDName: "Garden Supplies",
        subCats: [
          { subCatName: "BBQ" },
          { subCatName: "Watering n Irrigation" },
          { subCatName: "Garden Pots n Planters" },
          { subCatName: "Yard n Garden Decor" },
          { subCatName: "Fertilizer" },
          { subCatName: "Pest Control" },
          { subCatName: "Beekeeping Supplies" },
          { subCatName: "Mailboxes" },
          { subCatName: "Outdoor Heaters" },
          { subCatName: "Shade" },
          { subCatName: "Outdoor Hot Tubs n Accessories" },
          { subCatName: "Garden Buildings" },
          { subCatName: "Indoor Gardening n Hydroponics" },
          { subCatName: "Plant Support n Care" },
          { subCatName: "Pond Liners" },
          { subCatName: "Garden Carts" },
          { subCatName: "Seed Disseminators" },
        ],
      },
      {
        subDName: "Household Merchandises",
        subCats: [
          { subCatName: "Lighters n Smoking Accessories" },
          { subCatName: "Rain Gear" },
          { subCatName: "Dust Covers" },
          { subCatName: "Temperature Gauges" },
          { subCatName: "Warming Products" },
          { subCatName: "Moth n Mildew Proofing" },
        ],
      },
    ],
  },
  {
    departmentName: "Appliances n Fixtures",
    SubDepartments: [
      {
        subDName: "Light n Lighting",
        subCats: [
          { subCatName: "Lamps n Shades" },
          { subCatName: "Ceiling Lights n Fans" },
          { subCatName: "Light Bulbs" },
          { subCatName: "LED Lighting" },
          { subCatName: "Outdoor Lighting" },
          { subCatName: "LED Lamps" },
          { subCatName: "Portable Lighting" },
          { subCatName: "Commercial Lighting" },
          { subCatName: "Night Lights" },
          { subCatName: "Book Lights" },
          { subCatName: "Professional Lighting" },
          { subCatName: "Novelty Lighting" },
          { subCatName: "Holiday Lighting" },
          { subCatName: "Lighting Accessories" },
          { subCatName: "Under Cabinet Lights" },
          { subCatName: "Special Engineering Lighting" },
          { subCatName: "Vanity Lights" },
        ],
      },
      {
        subDName: "Smart Home",
        subCats: [
          { subCatName: "Automatic Curtain Control System" },
          { subCatName: "Smart Temperature Control System" },
          { subCatName: "Smart Home Control" },
          { subCatName: "Smart Human Body Sensors" },
        ],
      },
      {
        subDName: "Kitchen Appliances",
        subCats: [
          { subCatName: "Juicers" },
          { subCatName: "Food Processors" },
          { subCatName: "Ice Cream Makers" },
          { subCatName: "Electric Kettles" },
          { subCatName: "Dehydrators" },
          { subCatName: "Food Mixers" },
          { subCatName: "Coffee Makers" },
          { subCatName: "Yogurt Makers" },
          { subCatName: "Vacuum Food Sealers" },
          { subCatName: "Electric Coffee Grinders" },
          { subCatName: "Blenders" },
          { subCatName: "Coffee Roasters" },
          { subCatName: "Oil Pressers" },
          { subCatName: "Cooking Appliances" },
          { subCatName: "Electric Air Pots" },
          { subCatName: "Food Waste Disposers" },
          { subCatName: "Ice Crushers n Shavers" },
          { subCatName: "Meat Grinders" },
          { subCatName: "Multicookers" },
          { subCatName: "Popcorn Makers" },
          { subCatName: "Vegetable Washers" },
          { subCatName: "Electric Noodle Makers" },
          { subCatName: "Home Wine Making Machines" },
          { subCatName: "Coffee Machines" },
          { subCatName: "Milk Frothers" },
          { subCatName: "Hot Tea Makers" },
          { subCatName: "Electric Peelers" },
          { subCatName: "Soda Makers" },
          { subCatName: "Air Fryers" },
          { subCatName: "Capsule Coffee Machine" },
          { subCatName: "Reusable Coffee Capsules n Pods" },
        ],
      },
      {
        subDName: "Household Appliances",
        subCats: [
          { subCatName: "Small Air Conditioning Appliances" },
          { subCatName: "Cleaning Appliances" },
          { subCatName: "Water Treatment Appliances" },
          { subCatName: "Home Heaters" },
          { subCatName: "Laundry Appliances" },
          { subCatName: "Shoe Dryers" },
          { subCatName: "Wet Towel Dispensers" },
          { subCatName: "Hand Dryers" },
          { subCatName: "Shoe Polishing Equipment" },
        ],
      },
      {
        subDName: "Personal Care Appliances",
        subCats: [
          { subCatName: "Hair Dryers" },
          { subCatName: "Electric Shavers" },
          { subCatName: "Hair Trimmers" },
          { subCatName: "Electric Toothbrushes n Replacement Heads" },
          { subCatName: "Epilators" },
          { subCatName: "Personal Care Appliance Accessories" },
          { subCatName: "Hair Clippers" },
          { subCatName: "Oral Irrigators" },
          { subCatName: "Wax Heaters" },
          { subCatName: "Electronic Foot Files" },
          { subCatName: "Electric Hair Brushes" },
          { subCatName: "Electric Nose n Ear Trimmers" },
          { subCatName: "Hair Diffusers" },
          { subCatName: "Electric Hair Caps" },
          { subCatName: "Electric Bath Brushes" },
        ],
      },
      {
        subDName: "Major Appliances",
        subCats: [
          { subCatName: "Washing Machines" },
          { subCatName: "Water Heaters" },
          { subCatName: "Air Conditioners" },
          { subCatName: "Refrigerators n Freezers" },
          { subCatName: "Portable Washing Machines" },
          { subCatName: "Disinfecting Cabinets" },
          { subCatName: "Dish Washers" },
          { subCatName: "Ranges" },
          { subCatName: "Range Hoods" },
          { subCatName: "Bulit-in Induction Cookers" },
          { subCatName: "Bulit-in Ovens" },
          { subCatName: "Clothes Drying Machine" },
          { subCatName: "Bulit-in Microwave Ovens" },
          { subCatName: "Trash Compactors" },
        ],
      },
      {
        subDName: "Commercial Appliances",
        subCats: [
          { subCatName: "Food Filling Machines" },
          { subCatName: "Electric Slicers" },
          { subCatName: "Slush Machines" },
          { subCatName: "Pizza Cone Machines" },
          { subCatName: "Electric French Fry Cutters" },
          { subCatName: "Electric Spiral Potato Slicers" },
        ],
      },
      {
        subDName: "Home Appliance Parts",
        subCats: [
          { subCatName: "Cleaning Appliance Parts" },
          { subCatName: "Air Conditioning Appliance Parts" },
          { subCatName: "Laundry Appliance Parts" },
          { subCatName: "Personal Care Appliance Parts" },
          { subCatName: "Refrigerator n Freezer Parts" },
          { subCatName: "Kitchen Appliance Parts" },
          { subCatName: "Home Heater Parts" },
          { subCatName: "Water Heater Parts" },
          { subCatName: "Water Treatment Appliance Parts" },
          { subCatName: "Hand Dryer Parts" },
          { subCatName: "Wet Towel Dispenser Parts" },
        ],
      },
      {
        subDName: "Bathroom Fixtures",
        subCats: [
          { subCatName: "Bathroom Hardware" },
          { subCatName: "Bathroom Sinks,Faucets n Accessories" },
          { subCatName: "Shower Equipment" },
          { subCatName: "Bidets n Bidet Parts" },
          { subCatName: "Toilets n Toilet Parts" },
          { subCatName: "Sanitary Ware Suite" },
          { subCatName: "Spa Tubs n Sauna Rooms" },
          { subCatName: "Bathtubs n Whirlpools" },
          { subCatName: "Bathroom Safety n Accessories" },
          { subCatName: "Shower Rooms n Accessories" },
          { subCatName: "Bathroom Vanities" },
        ],
      },
      {
        subDName: "Kitchen Fixtures",
        subCats: [
          { subCatName: "Kitchen Faucets" },
          { subCatName: "Kitchen Faucet Accessories" },
          { subCatName: "Kitchen Cabinets n Accessories" },
          { subCatName: "Kitchen Sinks" },
          { subCatName: "Kitchen Sink Accessories" },
          { subCatName: "Wall Mounted Kitchen Racks" },
          { subCatName: "Kitchen Cabinet Storage" },
          { subCatName: "Water Filtration" },
        ],
      },
    ],
  },
  {
    departmentName: "Sports n Outdoor",
    SubDepartments: [
      {
        subDName: "Sports Clothing",
        subCats: [
          { subCatName: "Sports Bras" },
          { subCatName: "T shirts" },
          { subCatName: "Vests" },
          { subCatName: "Sets or Suits" },
          { subCatName: "Tights" },
          { subCatName: "Shirts" },
          { subCatName: "Children Sportswear n Accessories" },
          { subCatName: "Pants" },
          { subCatName: "Jackets" },
          { subCatName: "Shorts" },
          { subCatName: "Hoodies" },
          { subCatName: "Skorts" },
          { subCatName: "Jerseys" },
          { subCatName: "Base Layers" },
          { subCatName: "Skirts" },
          { subCatName: "Dresses" },
          { subCatName: "Robes" },
        ],
      },
      {
        subDName: "Sneakers",
        subCats: [
          { subCatName: "Running Shoes" },
          { subCatName: "Skateboarding Shoes" },
          { subCatName: "Basketball Shoes" },
          { subCatName: "Beach n Outdoor Sandals" },
          { subCatName: "Dance shoes" },
          { subCatName: "Hiking Shoes" },
          { subCatName: "Soccer Shoes" },
          { subCatName: "Walking Shoes" },
          { subCatName: "Sneaker Accessories" },
          { subCatName: "Tennis Shoes" },
          { subCatName: "Cycling Shoes" },
          { subCatName: "Skate Shoes" },
          { subCatName: "Golf Shoes" },
          { subCatName: "Badminton" },
          { subCatName: "Fitness n Cross-training Shoes" },
          { subCatName: "Toning Shoes" },
          { subCatName: "Table tennis shoes" },
          { subCatName: "Wrestling Shoes" },
          { subCatName: "Track n Field Shoes" },
          { subCatName: "Snowboarding n Skiing Shoes" },
          { subCatName: "Weightlifting Shoes" },
          { subCatName: "Volleyball Shoes" },
          { subCatName: "Fencing Shoes" },
          { subCatName: "Baseball Shoes" },
        ],
      },
      {
        subDName: "Water Sports",
        subCats: [
          { subCatName: "Surfing n Diving" },
          { subCatName: "Rowing Boats" },
          { subCatName: "Air Mattresses" },
          { subCatName: "Water Safety Products" },
          { subCatName: "Beach Caps" },
          { subCatName: "Racing Boats" },
          { subCatName: "Flying Discs" },
          { subCatName: "Water Sports Shoes" },
        ],
      },
      {
        subDName: "Swimming",
        subCats: [
          { subCatName: "Two-Piece Suits" },
          { subCatName: "One-Piece Suits" },
          { subCatName: "Childrens Swimwear" },
          { subCatName: "Swimming Accessories" },
          { subCatName: "Mens Swimwear" },
          { subCatName: "Two-Piece Separates" },
          { subCatName: "Body Suits" },
          { subCatName: "Muslim Swimwear" },
        ],
      },
      {
        subDName: "Sports Bags",
        subCats: [
          { subCatName: "Gym Bags" },
          { subCatName: "Hunting Bags" },
          { subCatName: "Sport Bags Covers" },
          { subCatName: "River Trekking Bags" },
          { subCatName: "City Jogging Bags" },
          { subCatName: "Racquet Sport Bags" },
          { subCatName: "Diving Bags" },
          { subCatName: "Skiing Bags" },
          { subCatName: "Training Bags" },
          { subCatName: "Surfing Bags" },
          { subCatName: "Athletic Bags" },
        ],
      },
      {
        subDName: "Fishing",
        subCats: [
          { subCatName: "Boats n Equipment" },
          { subCatName: "Fishing Accessories" },
          { subCatName: "Fishing Apparel" },
          { subCatName: "Fishing Bags" },
          { subCatName: "Fishing Chairs" },
          { subCatName: "Fish Finders" },
          { subCatName: "Fishing Float" },
          { subCatName: "Fishhooks" },
          { subCatName: "Fishing Lines" },
          { subCatName: "Fishing Lures" },
          { subCatName: "Fishing Reels" },
          { subCatName: "Fishing Tackle Boxes" },
          { subCatName: "Fishing Rods" },
          { subCatName: "Fishing Rope" },
          { subCatName: "Fishing Tools" },
          { subCatName: "Rod Combo" },
        ],
      },
      {
        subDName: "Hunting",
        subCats: [
          { subCatName: "Bow n Arrow" },
          { subCatName: "Hunting Optics" },
          { subCatName: "Hunting Cameras" },
          { subCatName: "Weapon Lights" },
          { subCatName: "Hunting Bags n Holsters" },
          { subCatName: "Hunting Decoy" },
          { subCatName: "Hunting Gun Accessories" },
          { subCatName: "Scope Mounts n Accessories" },
          { subCatName: "Tactical Headsets n Accessories" },
          { subCatName: "Blind n Tree Stand" },
        ],
      },
      {
        subDName: "Golf",
        subCats: [
          { subCatName: "Golf Shoe" },
          { subCatName: "Golf Training Aids" },
          { subCatName: "Golf Clubs" },
          { subCatName: "Golf Shirts" },
          { subCatName: "Golf Caps" },
          { subCatName: "Golf Bags" },
          { subCatName: "Golf Pants" },
          { subCatName: "Golf Trainning T Shirts" },
          { subCatName: "Golf Shorts" },
          { subCatName: "Golf Jackets" },
          { subCatName: "Golf Balls" },
          { subCatName: "Club Making Products" },
          { subCatName: "Golf Gloves" },
          { subCatName: "Golf Car Parts n Accessories" },
          { subCatName: "Marks" },
          { subCatName: "Golf Trolley" },
          { subCatName: "Golf Cars" },
        ],
      },
      {
        subDName: "Cycling",
        subCats: [
          { subCatName: "Bicycle" },
          { subCatName: "Bicycle Parts" },
          { subCatName: "Bicycle Accessories" },
          { subCatName: "Cycling Clothings" },
          { subCatName: "Bicycle Repair Tools" },
          { subCatName: "Electric Bicycle" },
          { subCatName: "Electric Bicycle Part" },
          { subCatName: "Electric Bicycle Accessories" },
        ],
      },
      {
        subDName: "Shootong",
        subCats: [
          { subCatName: "Paintball Accessories" },
          { subCatName: "Paintballs" },
        ],
      },
      {
        subDName: "Running",
        subCats: [
          { subCatName: "Running T Shirts" },
          { subCatName: "Running Jackets" },
          { subCatName: "Running Sets" },
          { subCatName: "Running Shorts" },
          { subCatName: "Running Pants" },
          { subCatName: "Running Bags" },
          { subCatName: "Running Socks" },
          { subCatName: "Running Arm Warmers" },
          { subCatName: "Track n Field Shoes" },
          { subCatName: "Running Gloves" },
        ],
      },
      {
        subDName: "Horse Racing",
        subCats: [
          { subCatName: "Horse Care Products" },
          { subCatName: "Halters" },
          { subCatName: "Body Protectors" },
          { subCatName: "Iding Crops n Spurs" },
          { subCatName: "Breeches" },
          { subCatName: "Saddle Pads" },
          { subCatName: "Saddles" },
          { subCatName: "Riding Gloves" },
          { subCatName: "Horseshoes" },
          { subCatName: "Horse Riding Boots" },
          { subCatName: "Horse Rugs" },
          { subCatName: "Chaps" },
        ],
      },
      {
        subDName: "Bowling",
        subCats: [
          { subCatName: "Bowlings" },
          { subCatName: "Bowling Shoes" },
          { subCatName: "Bowling Shirts" },
          { subCatName: "Bowling Jackets" },
        ],
      },
      {
        subDName: "Other Outdoor n Sports Equipment",
        subCats: [
          { subCatName: "Archery Equipment" },
          { subCatName: "Camping n Hiking Equipment" },
          { subCatName: "Equestrian Equipment" },
          { subCatName: "Skateboarding n Scooters" },
          { subCatName: "Skiing n Snowboarding" },
          { subCatName: "Racquet Sports" },
        ],
      },
    ],
  },
  {
    departmentName: "Education n Office Supplies",
    SubDepartments: [
      {
        subDName: "Writing n Correction Supplies",
        subCats: [
          { subCatName: "Pencil Cases n Bags" },
          { subCatName: "Ballpoint Pens" },
          { subCatName: "Gel Pens" },
          { subCatName: "Markers n Highlighters" },
          { subCatName: "Fountain Pens" },
          { subCatName: "Pencil Bags" },
          { subCatName: "Pencil Cases" },
          { subCatName: "Pencils" },
          { subCatName: "Stencils" },
          { subCatName: "Correction Supplies" },
          { subCatName: "Eraser" },
          { subCatName: "Colored Markers" },
          { subCatName: "Banner Pens" },
          { subCatName: "Pencil Sharpeners" },
          { subCatName: "Highlighters" },
          { subCatName: "Wooden Lead Pencils" },
          { subCatName: "Mechanical Pencils" },
          { subCatName: "Paint Markers" },
          { subCatName: "Pen refill" },
          { subCatName: "Wooden Colored Pencils" },
          { subCatName: "Correction Tape" },
          { subCatName: "Multi Function Pen" },
          { subCatName: "Whiteboard Marker" },
          { subCatName: "Rollerball Pens" },
          { subCatName: "Pen Grips" },
          { subCatName: "Ink Supplies" },
          { subCatName: "Correction Fluid" },
          { subCatName: "Fineliner" },
          { subCatName: "Roll up Pencil Bags" },
          { subCatName: "Electric Pencil Sharpeners" },
          { subCatName: "Pen Cover" },
          { subCatName: "Electric Eraser" },
          { subCatName: "Dip Pens" },
          { subCatName: "Smart Pens" },
          { subCatName: "Fountain Pen Nibs" },
          { subCatName: "Dot Markers" },
        ],
      },
      {
        subDName: "Notebooks n Writting Pads",
        subCats: [
          { subCatName: "Notebooks" },
          { subCatName: "Memo Pads" },
          { subCatName: "Drawing Notebooks" },
          { subCatName: "Planners" },
          { subCatName: "Clipboard" },
          { subCatName: "Padfolio" },
          { subCatName: "Sticky Notes" },
          { subCatName: "Filler Paper" },
          { subCatName: "Notebook Cover" },
          { subCatName: "Smart Notebooks" },
          { subCatName: "Composition Notebooks" },
          { subCatName: "Chart Tablets" },
        ],
      },
      {
        subDName: "School n Educational Supplies",
        subCats: [
          { subCatName: "Stationery Set" },
          { subCatName: "Drafting Supplies" },
          { subCatName: "Teaching Resources" },
          { subCatName: "Lab Supplies" },
          { subCatName: "Rulers" },
          { subCatName: "Educational Equipment" },
          { subCatName: "Map" },
          { subCatName: "Chalk" },
          { subCatName: "Compasses" },
          { subCatName: "Math Sets" },
          { subCatName: "Protractor" },
          { subCatName: "Assorted Stamp" },
          { subCatName: "Craft Ink Pads" },
          { subCatName: "Geometry Template" },
          { subCatName: "Globe" },
          { subCatName: "Electronic Dictionaries" },
          { subCatName: "Tutorial Bags" },
          { subCatName: "Pointer" },
          { subCatName: "Dry Erase Sleeves" },
        ],
      },
      {
        subDName: "Art Supplies",
        subCats: [
          { subCatName: "Oil Paints" },
          { subCatName: "Acrylic Paints" },
          { subCatName: "Water Color" },
          { subCatName: "Sketch Charcoal Bars" },
          { subCatName: "Sketch Charcoal Pencils" },
          { subCatName: "Art Sets" },
          { subCatName: "Calligraphy Brushes" },
          { subCatName: "Crayons" },
          { subCatName: "Easels" },
          { subCatName: "Oil Pastel" },
          { subCatName: "Paint Brushes" },
          { subCatName: "Painting Canvas" },
          { subCatName: "Painting Paper" },
          { subCatName: "Palette" },
          { subCatName: "Rice Paper" },
          { subCatName: "Stretched Canvas" },
          { subCatName: "Gouache Paints" },
          { subCatName: "Mineral Paints" },
          { subCatName: "Chinese Painting Pigment" },
          { subCatName: "Sketchbooks" },
          { subCatName: "Palette Cases" },
          { subCatName: "Palette Paper" },
          { subCatName: "Paint Sponges" },
          { subCatName: "Paint Daubers" },
          { subCatName: "Paint Brush Washer" },
          { subCatName: "Calligraphy Set" },
          { subCatName: "Paperweight" },
          { subCatName: "Water Writing Cloth" },
          { subCatName: "Felt Pads" },
          { subCatName: "Penholder" },
          { subCatName: "Copybook" },
          { subCatName: "Ink Stone" },
          { subCatName: "Drawing Paper" },
          { subCatName: "Tracing Paper" },
          { subCatName: "Watercolor Paper" },
          { subCatName: "Pastel Paper" },
          { subCatName: "Couplet Paper" },
          { subCatName: "Drawing Gloves" },
          { subCatName: "Color Cards" },
          { subCatName: "Coloring Book" },
          { subCatName: "Sand Painting" },
          { subCatName: "Electric Spray Pen" },
          { subCatName: "Art Storage Tube" },
          { subCatName: "Art Portfolio Case" },
          { subCatName: "Colored Pencils" },
        ],
      },
      {
        subDName: "Tapes Adhesives n Fasteners",
        subCats: [
          { subCatName: "Office Adhesive Tape" },
          { subCatName: "Washi Tape" },
          { subCatName: "Liquid Glue" },
          { subCatName: "Tape Dispenser" },
          { subCatName: "Glue Stick" },
          { subCatName: "Masking Tape" },
          { subCatName: "Rubber Bands" },
          { subCatName: "Double Sided Tape" },
          { subCatName: "Nano Tape" },
          { subCatName: "Transparent Tape" },
        ],
      },
      {
        subDName: "Desk Accessories n Organizer",
        subCats: [
          { subCatName: "Pen Holders" },
          { subCatName: "Bookends" },
          { subCatName: "Desk Set" },
          { subCatName: "Card Holder n Note Holder" },
          { subCatName: "Stationery Holder" },
          { subCatName: "Clip Holder n Clip Dispenser" },
          { subCatName: "File Tray" },
          { subCatName: "Key Holder n Keychain Organizer" },
          { subCatName: "Desk Pads n Blotters" },
          { subCatName: "Magazine Organizer" },
          { subCatName: "Business Card Holders" },
          { subCatName: "Letter Holder" },
          { subCatName: "Cable Organizers" },
          { subCatName: "Copyholders n Book Stands" },
          { subCatName: "Suggestion Boxes" },
        ],
      },
      {
        subDName: "Office Binding Supplies",
        subCats: [
          { subCatName: "Clips" },
          { subCatName: "Stapler" },
          { subCatName: "Hole Punch" },
          { subCatName: "Pin" },
          { subCatName: "Binding Combs n Spines" },
          { subCatName: "Staples" },
          { subCatName: "Staple Remover" },
          { subCatName: "Book Cover" },
          { subCatName: "Thumbtacks" },
          { subCatName: "Book Rings or Loose Leaf Binder" },
        ],
      },
      {
        subDName: "Labels Indexes n Stamps",
        subCats: [
          { subCatName: "Badge Holder n Accessories" },
          { subCatName: "Bookmark" },
          { subCatName: "Stamps" },
          { subCatName: "Inkpad" },
          { subCatName: "Ink Refills" },
        ],
      },
      {
        subDName: "Paper",
        subCats: [
          { subCatName: "Photo Paper" },
          { subCatName: "Copy Paper" },
          { subCatName: "A4 Paper" },
          { subCatName: "Letter Paper" },
          { subCatName: "Transfer Paper" },
          { subCatName: "Self Adhesive Paper" },
          { subCatName: "Thermal Fax Paper" },
          { subCatName: "Paper Roll" },
          { subCatName: "Cash Register Paper" },
          { subCatName: "Cards n Card Stock" },
          { subCatName: "Carbon Paper" },
          { subCatName: "Printer Paper" },
          { subCatName: "Carbonless Paper" },
          { subCatName: "Kraft paper" },
          { subCatName: "Rubbing Paper" },
          { subCatName: "Scratch Paper" },
        ],
      },
      {
        subDName: "Calendars Planners n Cards",
        subCats: [
          { subCatName: "Calendar" },
          { subCatName: "Business Cards" },
          { subCatName: "Card Holder" },
          { subCatName: "Certificate" },
        ],
      },
      {
        subDName: "Cutting Supplies",
        subCats: [
          { subCatName: "Utility Knife" },
          { subCatName: "Letter Opener" },
          { subCatName: "Scissors" },
          { subCatName: "Cutting Mats" },
        ],
      },
      {
        subDName: "Presentation Supplies",
        subCats: [
          { subCatName: "Whiteboard" },
          { subCatName: "Pins n Tacks" },
          { subCatName: "Blackboard" },
          { subCatName: "Drawing Board" },
          { subCatName: "Bulletin Board" },
          { subCatName: "Dry Erase Markers" },
          { subCatName: "Message Board" },
          { subCatName: "Flip Chart" },
          { subCatName: "Writing Board" },
          { subCatName: "Board Eraser" },
          { subCatName: "Interactive Whiteboard" },
          { subCatName: "Magnetic Board" },
          { subCatName: "Digital Drawing Tablets" },
          { subCatName: "Cork Boards" },
          { subCatName: "Magnet Sheets" },
          { subCatName: "Changeable Letter Boards" },
          { subCatName: "Fluorescent Boards" },
          { subCatName: "Roll Up Banners" },
        ],
      },
      {
        subDName: "Filing Products",
        subCats: [
          { subCatName: "File Folder" },
          { subCatName: "Document Bag" },
          { subCatName: "Expandable File" },
          { subCatName: "Presentation Folder" },
          { subCatName: "Clip File" },
          { subCatName: "Box File" },
          { subCatName: "File Jackets n File Pockets" },
          { subCatName: "Pocket Folders" },
          { subCatName: "File Storage Boxes" },
          { subCatName: "Elastic Closure Folder" },
          { subCatName: "Ring Binder" },
          { subCatName: "Hanging File Folder" },
          { subCatName: "Binder Index Dividers" },
          { subCatName: "Report Cover n Spine Bar" },
          { subCatName: "Lever Arch File" },
          { subCatName: "File Sorter" },
          { subCatName: "Binders" },
          { subCatName: "File Folder Labels" },
          { subCatName: "File Frames" },
        ],
      },
      {
        subDName: "Mail n Shipping Supplies",
        subCats: [
          { subCatName: "Paper Envelopes" },
          { subCatName: "Bubble Mailers" },
          { subCatName: "Box Mailers" },
        ],
      },
      {
        subDName: "School n Educational Supplies",
        subCats: [{ subCatName: "" }],
      },
      {
        subDName: "School n Educational Supplies",
        subCats: [
          { subCatName: "Education n Teaching" },
          { subCatName: "Arts n Photography" },
          { subCatName: "Life n Lifestyle" },
          { subCatName: "Literature n Fiction" },
          { subCatName: "Humanities n Social Science" },
          { subCatName: "Magazines" },
        ],
      },
      {
        subDName: "Stationery Sticker",
        subCats: [
          { subCatName: "Assorted Stickers" },
          { subCatName: "Name Sticker" },
        ],
      },
    ],
  },
  {
    departmentName: "Furniture",
    SubDepartments: [
      {
        subDName: "Home Furniture",
        subCats: [
          { subCatName: "Bedroom Furniture" },
          { subCatName: "Bathroom Furniture" },
          { subCatName: "Dining Room Furniture" },
          { subCatName: "Kitchen Furniture" },
          { subCatName: "Living Room Furniture" },
        ],
      },
      {
        subDName: "Office Furniture",
        subCats: [
          { subCatName: "Computer Desks" },
          { subCatName: "Conference Chairs" },
          { subCatName: "Laptop Desks" },
          { subCatName: "Magazine Racks" },
          { subCatName: "Office Chairs" },
          { subCatName: "Office Sofas" },
          { subCatName: "Reception Desks" },
        ],
      },
      {
        subDName: "Children Furniture",
        subCats: [
          { subCatName: "Children Beds" },
          { subCatName: "Children Cabinets" },
          { subCatName: "Children Chairs" },
          { subCatName: "Children Furniture Sets" },
          { subCatName: "Children Nightstands" },
          { subCatName: "Children Tables" },
          { subCatName: "Children Stools" },
          { subCatName: "Children Sofas" },
          { subCatName: "Children Wardrobes" },
        ],
      },
      {
        subDName: "Outdoor Furniture",
        subCats: [
          { subCatName: "Hammocks" },
          { subCatName: "Sun Loungers" },
          { subCatName: "Beach Chairs" },
          { subCatName: "Garden Chairs" },
          { subCatName: "Garden Furniture Sets" },
          { subCatName: "Garden Sofas" },
          { subCatName: "Outdoor Tables" },
          { subCatName: "Patio Benches" },
          { subCatName: "Patio Swings" },
          { subCatName: "Patio Umbrellas n Bases" },
          { subCatName: "Plant Shelves" },
          { subCatName: "Outdoor Bean Bag Sofas" },
        ],
      },
      {
        subDName: "Commercial Furniture",
        subCats: [
          { subCatName: "Hotel Furniture" },
          { subCatName: "Laboratory Furniture" },
          { subCatName: "Library Furniture" },
          { subCatName: "Restaurant Furniture" },
          { subCatName: "Salon Furniture" },
          { subCatName: "School Furniture" },
          { subCatName: "Theater Furniture" },
          { subCatName: "Waiting Chairs" },
        ],
      },
      {
        subDName: "Furniture Parts",
        subCats: [
          { subCatName: "Furniture Frames" },
          { subCatName: "Furniture Legs" },
        ],
      },
      {
        subDName: "Bar Furniture",
        subCats: [
          { subCatName: "Bar n Wine Cabinets" },
          { subCatName: "Bar Chairs" },
          { subCatName: "Bar Furniture Sets" },
          { subCatName: "Bar Stools" },
          { subCatName: "Bar Tables" },
        ],
      },
      {
        subDName: "Café Furniture",
        subCats: [
          { subCatName: "Café Chairs" },
          { subCatName: "Café Furniture Sets" },
          { subCatName: "Café Tables" },
        ],
      },
    ],
  },
  {
    departmentName: "Food n Beverages",
    SubDepartments: [
      {
        subDName: "Fresh Meats",
        subCats: [
          { subCatName: "Beef" },
          { subCatName: "Exotic Meats" },
          { subCatName: "Fowl" },
          { subCatName: "Game Meats" },
          { subCatName: "Lamb" },
          { subCatName: "Organ Meats" },
          { subCatName: "Pork" },
          { subCatName: "Veal" },
        ],
      },
      {
        subDName: "Processed Meats",
        subCats: [
          { subCatName: "Bacon" },
          { subCatName: "Dried Meat Products" },
          { subCatName: "Deli Meats" },
          { subCatName: "Hot dogs" },
          { subCatName: "Ham" },
          { subCatName: "Salami" },
          { subCatName: "Sausages" },
          { subCatName: "Salted and Cured Meat" },
          { subCatName: "Smoked Meat" },
          { subCatName: "Canned Meat" },
        ],
      },
      {
        subDName: "Sea Food",
        subDLongName: "Fresh Canned Or Smoked",
        subCats: [
          { subCatName: "Bass" },
          { subCatName: "Cod" },
          { subCatName: "Catfish" },
          { subCatName: "Flatfish" },
          { subCatName: "Flounder" },
          { subCatName: "Grouper" },
          { subCatName: "Haddock" },
          { subCatName: "Halibut" },
          { subCatName: "Salmon" },
          { subCatName: "Sardine" },
          { subCatName: "Swordfish" },
          { subCatName: "Spanish Mackerel" },
          { subCatName: "Sole" },
          { subCatName: "Tuna" },
          { subCatName: "Trout" },
        ],
      },
      {
        subDName: "Fats and Oils",
        subCats: [
          { subCatName: "Animal Fats" },
          { subCatName: "Avocado Oil" },
          { subCatName: "Coconut Oil" },
          { subCatName: "Extra Virgin Olive Oil" },
          { subCatName: "Grass fed Butter Or Ghee" },
          { subCatName: "MCT Oil" },
        ],
      },
      {
        subDName: "Snack Options",
        subCats: [
          { subCatName: "Bone Broth" },
          { subCatName: "Canned Fish" },
          { subCatName: "Canned Meat" },
          { subCatName: "Dried Meat products" },
          { subCatName: "Pepperoni slices" },
          { subCatName: "Pork rinds" },
          { subCatName: "Smoked Fish" },
          { subCatName: "Seaweed" },
        ],
      },
      {
        subDName: "Herbs Spices n Seasonings",
        subCats: [
          { subCatName: "Basil" },
          { subCatName: "Black Pepper" },
          { subCatName: "Chives" },
          { subCatName: "Cinnamon" },
          { subCatName: "Chili Powder" },
          { subCatName: "Curry Powder" },
          { subCatName: "Dill" },
          { subCatName: "Mustard" },
          { subCatName: "Most Sugar free Hot Sauces" },
          { subCatName: "Oregano" },
          { subCatName: "Rosemary" },
          { subCatName: "Salt" },
          { subCatName: "Thyme" },
        ],
      },
      {
        subDName: "Drinks and Beverages",
        subCats: [
          { subCatName: "Club Soda" },
          { subCatName: "Coffee" },
          { subCatName: "Sparkling Water" },
          { subCatName: "Seltzer Water" },
          { subCatName: "Soda Water" },
          { subCatName: "Tea" },
          { subCatName: "Water" },
        ],
      },
      {
        subDName: "Alcohol",
        subCats: [
          { subCatName: "Cognac" },
          { subCatName: "Brandy" },
          { subCatName: "Bourbon" },
          { subCatName: "Gin" },
          { subCatName: "Rum" },
          { subCatName: "Scotch" },
          { subCatName: "Tequila" },
          { subCatName: "Vodka" },
          { subCatName: "Whiskey" },
        ],
      },
    ],
  },
  {
    departmentName: "Security n Protection",
    SubDepartments: [
      {
        subDName: "Security n Protection",
        subCats: [
          { subCatName: "Surveillance Cameras" },
          { subCatName: "Surveillance System" },
          { subCatName: "Baby Monitors" },
          { subCatName: "Surveillance Video Recorder" },
          { subCatName: "CCTV Parts" },
          { subCatName: "CCTV Accessories" },
          { subCatName: "CCTV Monitor n Display" },
          { subCatName: "CCTV Camera Housings" },
          { subCatName: "DVR Cards" },
          { subCatName: "CCTV Microphone" },
          { subCatName: "CCTV Control System" },
        ],
      },
      {
        subDName: "Security Alarm",
        subCats: [
          { subCatName: "Sensor n Detector" },
          { subCatName: "Alarm System Kits" },
          { subCatName: "EAS System" },
          { subCatName: "Anti-Lost Alarm" },
          { subCatName: "Carbon Monoxide Detectors" },
          { subCatName: "Emergency Alarm Button" },
          { subCatName: "Anti-theft Lock" },
          { subCatName: "Alarm Host" },
          { subCatName: "Alarm Keyboard" },
          { subCatName: "Alarm Lamp" },
          { subCatName: "Alarm Remote Controller" },
          { subCatName: "Alarm Siren" },
          { subCatName: "Anti Candid Camera Detector" },
        ],
      },
      {
        subDName: "Access Control",
        subCats: [
          { subCatName: "Access Control Cards" },
          { subCatName: "Access Control Kits" },
          { subCatName: "Control Card Readers" },
          { subCatName: "Fingerprint Recognition Device" },
          { subCatName: "Access Control Accessories" },
          { subCatName: "Electric Lock" },
          { subCatName: "Access Control Keypads" },
          { subCatName: "Facial Recognition Device" },
          { subCatName: "Door Remote Control" },
          { subCatName: "Electric Door Control System" },
        ],
      },
      {
        subDName: "Workplace Safety Supplies",
        subCats: [
          { subCatName: "Masks" },
          { subCatName: "Safety Goggles" },
          { subCatName: "Safety Clothing" },
          { subCatName: "Safety Gloves" },
          { subCatName: "Ear Protector" },
          { subCatName: "Warning Tape" },
          { subCatName: "Safety Shoe Boots" },
          { subCatName: "Safety Harness" },
          { subCatName: "Safety Helmet" },
          { subCatName: "Kneepads" },
          { subCatName: "Safety Cones" },
          { subCatName: "Respirators" },
        ],
      },
      {
        subDName: "Door Intercom",
        subCats: [
          { subCatName: "Video Intercom" },
          { subCatName: "Doorbell" },
          { subCatName: "Audio Intercom" },
          { subCatName: "Indoor Monitor" },
          { subCatName: "Door Phone" },
          { subCatName: "Intercom Accessories" },
        ],
      },
      {
        subDName: "Fire Protection",
        subCats: [
          { subCatName: "Smoke Detector" },
          { subCatName: "Carbon Monoxide Detectors" },
          { subCatName: "Fire Respirators" },
          { subCatName: "Fire Extinguisher" },
          { subCatName: "Fire Blanket" },
          { subCatName: "Heat Detector" },
          { subCatName: "Fire Alarm Control Panel" },
          { subCatName: "Fire Escape Ladders" },
          { subCatName: "Fire Hose" },
          { subCatName: "Fire-proof Suit" },
          { subCatName: "Fire Broadcasting" },
        ],
      },
      {
        subDName: "Roadway Safety",
        subCats: [
          { subCatName: "Traffic Light" },
          { subCatName: "Traffic Signal" },
          { subCatName: "Reflective Material" },
          { subCatName: "Road Stud" },
          { subCatName: "Speed Bump" },
          { subCatName: "Traffic Barrier" },
        ],
      },
      {
        subDName: "Other Utilities",
        subCats: [
          { subCatName: "Lightning Protection" },
          { subCatName: "Transmission n Cables" },
          { subCatName: "Security Inspection Device" },
          { subCatName: "IoT Devices" },
        ],
      },
    ],
  },
  {
    departmentName: "Machinery, Industrial Parts n Tools",
    SubDepartments: [
      {
        subDName: "Machinery",
        subCats: [
          { subCatName: "Agriculture " },
          { subCatName: "Machinery n Equipment" },
          { subCatName: "Apparel n Textile Machinery" },
          { subCatName: "Building Material Machinery" },
          { subCatName: "Chemical Machinery n Equipment" },
          { subCatName: "Electronic Products Machinery" },
          { subCatName: "Energy n Mineral Equipment" },
          { subCatName: "Engineering n Construction Machinery" },
          { subCatName: "Food n Beverage Machinery" },
          { subCatName: "General Industrial Equipment" },
          { subCatName: "Home Product Making Machinery" },
          { subCatName: "Industry Laser Equipment" },
          { subCatName: "Machine Tool Equipment" },
          { subCatName: "Metal n Metallurgy Machinery" },
          { subCatName: "Other Machinery n Industry Equipment" },
          { subCatName: "Packaging Machine" },
          { subCatName: "Paper Production Machinery" },
          { subCatName: "Pharmaceutical Machinery" },
          { subCatName: "Plastic n Rubber Machinery" },
          { subCatName: "Printing Machine" },
          { subCatName: "Refrigeration n Heat Exchange Equipment" },
          { subCatName: "Used Machinery n Equipment" },
          { subCatName: "Woodworking Machinery" },
        ],
      },
      {
        subDName: "Fabrication Services",
        subCats: [
          { subCatName: "Custom Fabrication Services" },
          { subCatName: "General Mechanical Components Design Services" },
          { subCatName: "General Mechanical Components Stock" },
          { subCatName: "Industrial Brake" },
          { subCatName: "Machine Tools Accessory" },
          { subCatName: "Moulds" },
          { subCatName: "Other General Mechanical Components" },
          { subCatName: "Other Mechanical Parts" },
          { subCatName: "Used General Mechanical Components" },
          { subCatName: "Coating Services" },
        ],
      },
      {
        subDName: "Tools n Hardware",
        subCats: [
          { subCatName: "Hardware" },
          { subCatName: "Hand Tools" },
          { subCatName: "Material Handling Tools" },
          { subCatName: "Power Tool Accessories" },
          { subCatName: "Power Tools" },
          { subCatName: "Tool Design Services" },
          { subCatName: "Tool Parts" },
          { subCatName: "Tool Processing Services" },
          { subCatName: "Tool Sets" },
          { subCatName: "Tool Stock" },
          { subCatName: "Knife" },
          { subCatName: "Hand Carts n Trolleys" },
          { subCatName: "Lawn Mower" },
          { subCatName: "Sander" },
        ],
      },
    ],
  },
];
